# Generated by Django 4.2.1 on 2023-05-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
